import "./globals.css";
import ErrorBoundary from "@/app/ErrorBoundary";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ErrorBoundary>
        {children}
      </ErrorBoundary>
      </body>
    </html>
  );
}
